---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: sip
  description: Everything related to SIP
spec:
  owner: sip-team
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: sip-resources
  description: Handy tools to keep artists in the loop
spec:
  owner: sip-team
  domain: sip
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: marvin
  description: This service help us manage our stagings via Slack
  tags:
    - python
    - slack-bot
spec:
  type: service
  lifecycle: production
  owner: sip-team
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: devops-datastore
  description: Stores staging details
spec:
  type: database
  owner: sip-team
  system: sip-resources
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sip-team
  description: The Security Infrastructure Performance group
spec:
  type: team
  profile:
    displayName: SIP Team
  children: []
  members: []
