---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: marvin
  description: This service help us manage our stagings via Slack
  tags:
    - python
    - slack-bot
  links:
    - url: https://github.com/test-IO/bot-marvin
      title: Repository
      icon: GitHub
spec:
  type: service
  lifecycle: production
  owner: sip-team
  system: sip-resources
  dependsOn:
    - resource:default/devops-datastore
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: devops-datastore
  description: Stores staging details
  links:
    - url: https://console.cloud.google.com/datastore/databases?referrer=search&orgonly=true&project=devops-oi&supportedpurview=organizationId
      title: Datastore Dashboard
      icon: dashboard
spec:
  type: database
  lifecycle: production
  owner: sip-team
  system: sip-resources
